// react/news-sys/src/App.js
/*
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-10-19 09:55:40
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-10-20 16:35:00
 * @Descripttion: 
 */
import './App.css';
import IndexRouter from './router/IndexRouter'

function App() {
  return (
    <div className="App">
      <IndexRouter></IndexRouter>
    </div>
  );
}

export default App;

// vue/vue2/permissionMg/src/App.vue
<!--
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-08-15 10:26:57
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-08-15 11:53:56
 * @Descripttion: 
-->
<template>
  <div id="app">
    <router-view />
  </div>
</template>

<script>
export default {
  name: "App"
};
</script>

<style scoped></style>
