// react/react-redux-demo/src_redux/App.jsx
/*
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-09-11 15:08:00
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-09-11 15:14:13
 * @Descripttion: 
 */
import React, { Component } from 'react'
import Count from './components/Count'


export default class App extends Component {
    render() {
        return (
            <div>
                <Count></Count>
            </div>
        )
    }
}

// vue/vue2/permissionMg/src/App.vue
<!--
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-08-15 10:26:57
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-08-15 11:53:56
 * @Descripttion: 
-->
<template>
  <div id="app">
    <router-view />
  </div>
</template>

<script>
export default {
  name: "App"
};
</script>

<style scoped></style>
