// vue/vue2/permissionMg/src/App.vue
<!--
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-08-15 10:26:57
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-08-15 11:53:56
 * @Descripttion: 
-->
<template>
  <div id="app">
    <router-view />
  </div>
</template>

<script>
export default {
  name: "App"
};
</script>

<style scoped></style>

// react/react-redux-demo/src_mobx/App.jsx
/*
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-09-11 15:08:00
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-10-08 13:00:34
 * @Descripttion: 
 */
import React, { Component } from 'react'
import Demo from './02_严格模式'


export default class App extends Component {
    render() {
        return (
            <div>
                <Demo></Demo>
            </div>
        )
    }
}
