// react/react-router-demo/src/pages/Home/index.jsx
/*
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-09-08 17:18:52
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-09-09 10:29:19
 * @Descripttion: 
 */
import { NavLink, Route, Switch, Redirect } from 'react-router-dom';
import React, { Component } from 'react'
import News from './News'
import Message from './Message'

export default class home extends Component {
    render() {
        return (
            <div>
                <span>home</span>
                <ul className="nav nav-tabs">
                    <li className="nav-item">
                        <NavLink className="nav-link" to='/home/news'>新闻</NavLink>
                    </li>
                    <li className="nav-item">
                        <NavLink className="nav-link" to='/home/message'>消息</NavLink>
                    </li>
                </ul>
                <Switch>
                    <Route path='/home/news' component={News}></Route>
                    <Route path='/home/message' component={Message}></Route>
                    <Redirect to='/home/news'></Redirect>
                </Switch>
            </div>
        )
    }
}

// vue/vue2/ssr/src/components/home.vue
<!--
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-08-17 16:52:51
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-08-18 14:53:41
 * @Descripttion: 
-->
<template>
    <div>
        <h1>{{ msg }}，这是首页</h1>
        {{ $store.state.counter }}
        {{ $store.getters.doubleCounter }}
        <button @click="$store.dispatch('addAsync', 1)">增加</button>
        <button @click="$store.dispatch('addAsync', -1)">减少</button>
    </div>
</template>

<script>
export default {
    name: 'home',
    data() {
        return {
            msg: '你好',
        }
    },
    asyncData({ store, route }) {
        return store.dispatch('addAsync', -1)
    },
}
</script>

<style scoped></style>
