// react/react-router6-demo/src/pages/Home.jsx
/*
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2022-09-13 10:37:16
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2022-09-13 11:20:45
 * @Descripttion: 
 */
import React from 'react'
import { NavLink, Outlet } from 'react-router-dom'

export default function Home() {
    return (
        <div>
            <span>home</span>
            <ul className="nav nav-tabs">
                <li className="nav-item">
                    <NavLink className="nav-link" to='news'>新闻</NavLink>
                </li>
                <li className="nav-item">
                    <NavLink className="nav-link" to='message'>消息</NavLink>
                </li>
            </ul>
            <Outlet />
        </div>
    )
}

// vue/vue3/webpack_ts_demo/src/views/Home.vue
<!--
 * @Author: mengbing mengbingg@outlook.com
 * @Date: 2023-01-29 11:11:45
 * @LastEditors: mengbing mengbingg@outlook.com
 * @LastEditTime: 2023-01-29 11:55:03
 * @Descripttion: 
-->
<template>
  <svg-icon icon-name="icon-vue" :size="30" fillColor="red"></svg-icon>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Home',
  components: {
  },
});
</script>
